name: Build and run unit test in DEV branch

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Project code checkout
      uses: actions/checkout@v4
    - name: Setup .NET version 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Run unit tests
      run: dotnet test SoftUniBazar.Tests/SoftUniBazar.Tests.csproj --no-build --verbosity normal
