name: Build and run tests

on:
  push:
    branches: [ "develop", "staging" ]

jobs:
  build_run_unit_tests:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    name: Build and Run Unit Tests

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET v6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Execute Unit Tests
      run: dotnet test SoftUniBazar.Tests/SoftUniBazar.Tests.csproj --no-build --verbosity normal

  build_run_integration_tests:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    name: Build and Run Integration Tests

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET v6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Execute Integration Tests
      run: dotnet test SoftUniBazar.IntegrationTests/SoftUniBazar.IntegrationTests.csproj --no-build --verbosity normal
