name: Build_init_tests
on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository 
      uses: actions/checkout@v4
    - name: Setup .NET version 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SoftUniBazar/SoftUniBazar.csproj

    - name: Build
      run: dotnet build --no-restore
    - name: Execute Unit Tests
      run: dotnet test SoftUniBazar.Tests/SoftUniBazar.Tests.csproj --no-build --verbosity normal
