name: Build and Run Unit Tests

on:
  push:
    branches: [ "develop" ]


jobs:
  Build_Unit_Tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET version 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Unit Tests
      run: dotnet build --no-restore
    - name: Execute Unit Tests
      run: dotnet test SoftUniBazar.Tests/SoftUniBazar.Tests.csproj --no-build --verbosity normal

