name: Build project and run integration tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build_project_run_integration_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET version 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Execute integration tests
      run: dotnet test SoftUniBazar.IntegrationTests/SoftUniBazar.IntegrationTests.csproj --no-build --verbosity normal
