# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Integration test

on:
  push:
    branches: [ "staging" ]

jobs:
  BuildAndIntegrationTest:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build the application 
      run: dotnet build --no-restore
    
    - name: Integration test
      run: dotnet test SoftUniBazar.IntegrationTests/SoftUniBazar.IntegrationTests.csproj --no-build --verbosity normal
